### PR TITLE
Added nickname management interface

### PR DESCRIPTION
**Pull request by finlaywashere**
- Added a management menu to search for users and set nicknames
- Also supports setting user's name colours

### CODE REVIEW

**Comment by grantmwilson** [comment]
Don't think you updated the common_models to the updated commit as I get the error: `'DiscordGuild' object has no attribute 'get_role'`

**Comment by finlaywashere** [comment]
I just had a look and `common_models` on the `finlaywashere/nicknames` is at [106b079](https://github.com/engfrosh/common_models/tree/106b079fbb7f23eac0693c7377259f0137e1d122) which is the same as main on common_models which contains those changes, are you sure you're on the main branch of common_models and not on the `tickets` branch?

**Comment by grantmwilson** [comment]
I ran `git submodule update --init` and common_models gets pointed to 6e4682fc so it probably just didn't get updated to the latest commit. I'll jump to the latest manually

**Comment by grantmwilson** [comment]
That seems to have fixed that error, however a question, does it always change both, or can it be used just to change just one or the other (color or nick)?

**Comment by finlaywashere** [comment]
It currently will always change both, however it defaults to discord's default role colour so it will only have an effect on the nickname if the user doesn't have a colour

**Pull request merged**
